const overskrift = document.querySelector("h1");
console.log(overskrift);
const underoverskrift = document.querySelector("h2");
console.log(underoverskrift);
const lilleo = document.querySelector("h3");
console.log(lilleo);
const tekst = document.querySelector("p");
console.log(tekst);
const footer = document.querySelector("footer");
console.log(footer);
